curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &
curl -k https://localhost:44362/api/simpleExample/block-example-async/60 &